const forgotPasswordStyles = {
    page: {
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#ffffff',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        color: '#f8fafc',
    },
    card: {
        width: '380px',
        background: '#f8f8f8',
        border: '1px solid #1f2937',
        borderRadius: '20px',
        padding: '32px 28px 26px',
        boxShadow: '0 18px 60px rgba(15, 23, 42, 0.35)',
    },
    iconWrap: {
        width: '48px',
        height: '48px',
        borderRadius: '14px',
        background: '#1f2937',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '18px',
    },
    title: {
        fontSize: '24px',
        fontWeight: '700',
        color: '#f8fafc',
        marginBottom: '6px',
    },
    sub: {
        fontSize: '13px',
        color: '#94a3b8',
        marginBottom: '22px',
        lineHeight: 1.5,
    },
    steps: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        marginBottom: '20px',
    },
    stepItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    stepDot: {
        width: '24px',
        height: '24px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '12px',
        fontWeight: '700',
    },
    stepLine: (active) => ({
        flex: 1,
        height: '2px',
        background: active ? '#3b82f6' : '#334155',
        borderRadius: '2px',
        transition: 'background 0.3s',
    }),
    stepLabel: {
        fontSize: '11px',
        fontWeight: '600',
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
    },
    hr: {
        border: 'none',
        borderTop: '1px solid #1f2937',
        marginBottom: '20px',
    },
    field: {
        marginBottom: '16px',
    },
    label: {
        display: 'block',
        fontSize: '11px',
        fontWeight: '600',
        letterSpacing: '0.08em',
        color: '#94a3b8',
        textTransform: 'uppercase',
        marginBottom: '8px',
    },
    inputWrap: {
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
    },
    iconLeft: {
        position: 'absolute',
        left: '12px',
        color: '#94a3b8',
        pointerEvents: 'none',
    },
    input: {
        width: '100%',
        padding: '12px 12px 12px 40px',
        background: '#111827',
        border: '1px solid #334155',
        borderRadius: '12px',
        fontSize: '14px',
        color: '#f8fafc',
        outline: 'none',
        fontFamily: 'inherit',
        transition: 'border-color 0.15s, background 0.15s',
        boxSizing: 'border-box',
    },
    eyeBtn: {
        position: 'absolute',
        right: '12px',
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        color: '#94a3b8',
        display: 'flex',
        alignItems: 'center',
        padding: 0,
    },
    resendBtn: {
        marginTop: '8px',
        background: 'transparent',
        border: 'none',
        color: '#60a5fa',
        fontSize: '12px',
        fontWeight: '600',
        cursor: 'pointer',
        padding: 0,
        fontFamily: 'inherit',
    },
    errorMsg: {
        padding: '12px 14px',
        background: '#1f2937',
        border: '1px solid #334155',
        borderRadius: '12px',
        color: '#f87171',
        fontSize: '13px',
        marginBottom: '14px',
    },
    successMsg: {
        padding: '12px 14px',
        background: '#112a44',
        border: '1px solid #1d4ed8',
        borderRadius: '12px',
        color: '#60a5fa',
        fontSize: '13px',
        marginBottom: '14px',
    },
    btn: {
        width: '100%',
        padding: '12px',
        background: '#2563eb',
        color: '#fff',
        border: 'none',
        borderRadius: '12px',
        fontSize: '14px',
        fontWeight: '700',
        cursor: 'pointer',
        fontFamily: 'inherit',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        transition: 'background 0.15s',
    },
    footer: {
        textAlign: 'center',
        fontSize: '13px',
        color: '#94a3b8',
        marginTop: '20px',
    },
    link: {
        color: '#60a5fa',
        textDecoration: 'none',
        fontWeight: '600',
    },
};

export default forgotPasswordStyles;