const orderStyles = {
    page: { display: 'flex', minHeight: '100vh', background: '#111827', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' },
    main: { flex: 1, marginLeft: '220px', padding: '28px 32px' },
    header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
    pageTitle: { fontSize: '22px', fontWeight: '600', color: '#f9fafb', margin: 0 },
    pageSubtitle: { fontSize: '13px', color: '#6b7280', marginTop: '4px' },
    addBtn: { display: 'flex', alignItems: 'center', gap: '8px', background: '#2563eb', color: '#fff', border: 'none', borderRadius: '8px', padding: '10px 16px', fontSize: '14px', fontWeight: '500', cursor: 'pointer', fontFamily: 'inherit', transition: 'background 0.15s' },
    searchWrap: { position: 'relative', marginBottom: '20px' },
    searchIcon: { position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280', pointerEvents: 'none' },
    searchInput: { width: '100%', padding: '10px 12px 10px 38px', background: '#1f2937', border: '1px solid #374151', borderRadius: '8px', fontSize: '14px', color: '#f9fafb', outline: 'none', fontFamily: 'inherit', transition: 'border-color 0.15s', boxSizing: 'border-box' },
    tableCard: { background: '#1f2937', borderRadius: '12px', border: '1px solid #374151', overflow: 'hidden' },
    table: { width: '100%', borderCollapse: 'collapse' },
    th: { textAlign: 'left', padding: '12px 20px', fontSize: '12px', fontWeight: '500', color: '#6b7280', letterSpacing: '0.04em', borderBottom: '1px solid #374151' },
    td: { padding: '14px 20px', fontSize: '13px', color: '#d1d5db', borderTop: '1px solid #374151' },
    tr: { transition: 'background 0.1s' },
    emptyCell: { padding: '40px', textAlign: 'center', color: '#4b5563', fontSize: '14px' },
    badge: { display: 'inline-block', padding: '3px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: '600' },
    editBtn: { display: 'flex', alignItems: 'center', gap: '5px', padding: '5px 10px', background: 'transparent', border: '1px solid #1e3a5f', borderRadius: '6px', color: '#60a5fa', fontSize: '12px', cursor: 'pointer', fontFamily: 'inherit', transition: 'background 0.15s' },
    deleteBtn: { display: 'flex', alignItems: 'center', gap: '5px', padding: '5px 10px', background: 'transparent', border: '1px solid #3b0a0a', borderRadius: '6px', color: '#f87171', fontSize: '12px', cursor: 'pointer', fontFamily: 'inherit', transition: 'background 0.15s' },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' },
    modalTitle: { fontSize: '17px', fontWeight: '600', color: '#f9fafb', margin: 0 },
    closeBtn: { background: 'none', border: 'none', color: '#6b7280', fontSize: '18px', cursor: 'pointer', padding: '0', lineHeight: 1 },
    field: { marginBottom: '14px' },
    label: { display: 'block', fontSize: '11px', fontWeight: '600', letterSpacing: '0.07em', color: '#6b7280', textTransform: 'uppercase', marginBottom: '6px' },
    cancelBtn: { flex: 1, padding: '10px', background: 'transparent', border: '1px solid #374151', borderRadius: '8px', color: '#d1d5db', fontSize: '14px', cursor: 'pointer', fontFamily: 'inherit', transition: 'background 0.15s' },
    submitBtn: { flex: 1, padding: '10px', background: '#2563eb', border: 'none', borderRadius: '8px', color: '#fff', fontSize: '14px', fontWeight: '500', cursor: 'pointer', fontFamily: 'inherit', transition: 'background 0.15s' },
    selectInput: { width: '100%', padding: '10px 12px', background: '#111827', border: '1px solid #374151', borderRadius: '8px', fontSize: '14px', color: '#f9fafb', outline: 'none', fontFamily: 'inherit', boxSizing: 'border-box' },
};

export default orderStyles;